ARG PYTHON_IMAGE
FROM ${PYTHON_IMAGE}

ARG APP_WORKDIR
ARG UVICORN_PORT

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR ${APP_WORKDIR}

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE ${UVICORN_PORT}