"""init

Revision ID: 4585c1b22698
Revises: 
Create Date: 2026-05-05 06:02:23.472705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4585c1b22698'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievement', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Achievement ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('achievement', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Achievement's name",
               existing_nullable=False)
    op.alter_column('achievement', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Achievement's description",
               existing_nullable=False)
    op.alter_column('achievement', 'condition_value',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='It is the condition to unlock the achievement',
               existing_nullable=False)
    op.alter_column('achievement', 'icon_url',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Icon's URL of local files",
               existing_nullable=False)
    op.alter_column('ai_log', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='AI log ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ai_log', 'decision_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Reason for the system's AI decision",
               existing_nullable=False)
    op.alter_column('ai_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when AI log was made',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_log', 'ai_decision',
               existing_type=postgresql.ENUM('APROBADO', 'RECHAZADO', name='ai_decision_enum'),
               comment=None,
               existing_comment="Decision made by the sistem's AI",
               existing_nullable=False)
    op.alter_column('ai_log', 'evaluation_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="JSON with information needed for the system's AI",
               existing_nullable=False)
    op.alter_column('ai_log', 'final_user_decision',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True = approved, False = disapproved',
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship28'), table_name='ai_log')
    op.drop_index(op.f('IX_Relationship32'), table_name='ai_log')
    op.alter_column('app_user', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Personal id for each user',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('app_user', 'username',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Unique username for each user',
               existing_nullable=False)
    op.alter_column('app_user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's password",
               existing_nullable=False)
    op.alter_column('app_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when user where created in the system',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('IX_Relationship12'), table_name='app_user')
    op.drop_index(op.f('IX_Relationship25'), table_name='app_user')
    op.alter_column('camp', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Camp ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('camp', 'name',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment="Camp's name",
               existing_nullable=False)
    op.alter_column('camp', 'location',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Camp's location",
               existing_nullable=False)
    op.alter_column('camp', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when camp was created',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('camp', 'session_time',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='How mucho a session can long in minutes (its the cookies time session value) ',
               existing_nullable=False)
    op.alter_column('daily_ration_log', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID for each daily ration log',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('daily_ration_log', 'persons_fed',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of persons who have been fed',
               existing_nullable=False)
    op.alter_column('daily_ration_log', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when daily ration were executed in the system (once per day)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('IX_Relationship31'), table_name='daily_ration_log')
    op.alter_column('exploration', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Exploration ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('exploration', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the exploration started',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('exploration', 'return_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the explorers return to the camp',
               existing_nullable=True)
    op.alter_column('exploration', 'exploration_status',
               existing_type=postgresql.ENUM('EN PROCESO', 'COMPLETADA', 'CANCELADA', name='exploration_status_enum'),
               comment=None,
               existing_comment="Exploration's status ('EN PROCESO', 'COMPLETADA', 'CANCELADA')",
               existing_nullable=False)
    op.alter_column('exploration', 'extra_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Extra days of exploration if they are needed',
               existing_nullable=False)
    op.alter_column('exploration', 'ration_per_person',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ration per person per day',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('exploration', 'max_extra_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of extra days a exploration could last',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('exploration', 'estimated_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of estimated days for a exploration',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('IX_Relationship29'), table_name='exploration')
    op.alter_column('exploration_loot', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Exploration loot ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('exploration_loot', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantity of loot collected in the exploration',
               existing_nullable=False)
    op.alter_column('exploration_loot', 'is_added_to_inventory',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='To check if the exploration loot have been added to the inventory or not',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('IX_Relationship16'), table_name='exploration_loot')
    op.drop_index(op.f('IX_Relationship17'), table_name='exploration_loot')
    op.alter_column('inventory', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Inventory's id",
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('inventory', 'maximum_stock',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Its the capacity of storage in the inventory',
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship15'), table_name='inventory')
    op.alter_column('inventory_movement', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Inventory Movement ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('inventory_movement', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date when movement in inventory was made',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory_movement', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantity of the resource being move',
               existing_nullable=False)
    op.alter_column('inventory_movement', 'movement_type',
               existing_type=postgresql.ENUM('SALIDA', 'INGRESO', 'TRANSFERENCIA', name='movement_type_enum'),
               comment=None,
               existing_comment="Movement type ('SALIDA', 'INGRESO', 'TRANSFERENCIA').",
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship14'), table_name='inventory_movement')
    op.alter_column('inventory_resource', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Inventory Resource ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('inventory_resource', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Resource quantity that is stored in the inventory',
               existing_nullable=False)
    op.alter_column('inventory_resource', 'minimum_stock_level',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Its the minimum level before notify the system',
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship10'), table_name='inventory_resource')
    op.drop_index(op.f('IX_Relationship9'), table_name='inventory_resource')
    op.alter_column('permission', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Permission ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('permission', 'name',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment="Permission's name",
               existing_nullable=False)
    op.alter_column('permission', 'description',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Permission's description about what it can do.",
               existing_nullable=False)
    op.alter_column('person', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Personal id for each person',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('person', 'name',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment="Person's first name",
               existing_nullable=False)
    op.alter_column('person', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Person's last name",
               existing_nullable=False)
    op.alter_column('person', 'age',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Person's age",
               existing_nullable=False)
    op.alter_column('person', 'background_info',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Person's background info about its days surviving the apocalypse",
               existing_nullable=False)
    op.alter_column('person', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment="Person's weight",
               existing_nullable=False)
    op.alter_column('person', 'height',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment="Person's height",
               existing_nullable=False)
    op.alter_column('person', 'current_status',
               existing_type=postgresql.ENUM('TRABAJANDO', 'EN EXPLORACIÓN', 'TRASLADANDO RECURSOS', 'LIBRE', name='current_status_enum'),
               comment=None,
               existing_comment="Current status ('TRABAJANDO', 'EN EXPLORACIÓN', 'TRASLADANDO RECURSOS', 'LIBRE')",
               existing_nullable=False)
    op.alter_column('person', 'health_status',
               existing_type=postgresql.ENUM('SANO', 'HERIDO', 'ENFERMO', 'MUERTO', name='health_status_enum'),
               comment=None,
               existing_comment="Person's health status ('SANO', 'HERIDO', 'ENFERMO', 'MUERTO')",
               existing_nullable=False)
    op.alter_column('person', 'camp_entry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the person arrived in the camp',
               existing_nullable=False)
    op.alter_column('person', 'photo_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Photo's url where is save locally",
               existing_nullable=False)
    op.alter_column('person', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='To check if person is active or not in the system',
               existing_nullable=False)
    op.alter_column('person', 'id_card',
               existing_type=sa.VARCHAR(length=250),
               comment=None,
               existing_comment='Identification card for each Person',
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship13'), table_name='person')
    op.alter_column('production_log', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID for each production log',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('production_log', 'actual_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Actual quantity produced',
               existing_nullable=False)
    op.alter_column('production_log', 'expected_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='This is the expected quantity based on entity profession_production',
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship34'), table_name='production_log')
    op.drop_index(op.f('IX_Relationship35'), table_name='production_log')
    op.drop_index(op.f('IX_Relationship36'), table_name='production_log')
    op.drop_index(op.f('IX_Relationship37'), table_name='production_log')
    op.alter_column('profession', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Profession's id",
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profession', 'is_critical',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Attribute to check if a profession is in a critical situation or not. Basically if there is not workers available the situation is critical (true).',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('profession', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Profession's name",
               existing_nullable=False)
    op.alter_column('profession_assignment', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Profession assignment ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profession_assignment', 'start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date when person started his profession in the camp',
               existing_nullable=False)
    op.alter_column('profession_assignment', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date when person ended its profession (in critical cases).',
               existing_nullable=True)
    op.alter_column('profession_assignment', 'reason',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Reason for the assignment in the profession',
               existing_nullable=False)
    op.alter_column('profession_assignment', 'is_main_profession',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Boolean to check if the assignment profession is its main job or not',
               existing_nullable=False)
    op.alter_column('profession_assignment', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Boolean to check if the assignment is active or not',
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship5'), table_name='profession_assignment')
    op.drop_index(op.f('IX_Relationship6'), table_name='profession_assignment')
    op.alter_column('profession_production', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Profession production ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profession_production', 'production_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantity of resources obtained in production',
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship18'), table_name='profession_production')
    op.drop_index(op.f('IX_Relationship19'), table_name='profession_production')
    op.alter_column('resource', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Resource's id",
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('resource', 'name',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment="Resource's name",
               existing_nullable=False)
    op.alter_column('resource', 'category',
               existing_type=postgresql.ENUM('ALIMENTO', 'BEBIDAS', 'SEMILLAS', 'MEDICINAS', name='resource_category_enum'),
               comment=None,
               existing_comment="Resource's category ('ALIMENTOS', 'BEBIDAS', 'SEMILLAS','MEDICINAS')",
               existing_nullable=False)
    op.alter_column('role', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Role ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment="Role's name",
               existing_nullable=False)
    op.alter_column('role', 'description',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Short description about the role',
               existing_nullable=False)
    op.alter_column('transfer_participants', 'is_transfer_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Attribute to check if the participant is in an active transfer\n',
               existing_nullable=False)
    op.alter_column('transfer_request', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Transfer request ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transfer_request', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date when the request was created',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transfer_request', 'from_camp_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Camp ID from the request is made',
               existing_nullable=False)
    op.alter_column('transfer_request', 'to_camp_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Camp ID where the request is sent',
               existing_nullable=False)
    op.alter_column('transfer_request', 'request_status',
               existing_type=postgresql.ENUM('PENDIENTE', 'APROBADO', 'RECHAZADO', name='request_status_enum'),
               comment=None,
               existing_comment="Request's status ('PENDIENTE', 'APROBADA', 'RECHAZADA')",
               existing_nullable=False)
    op.alter_column('transfer_request', 'transfer_status',
               existing_type=postgresql.ENUM('EN PREPARACIÓN', 'DE CAMINO', 'LLEGÓ', name='transfer_status_enum'),
               comment=None,
               existing_comment="Transfer's status ('EN PREPARACIÓN', 'DE CAMINO', 'LLEGÓ')",
               existing_nullable=True)
    op.alter_column('transfer_request', 'arrival_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date the requested transfer arrived at the camp',
               existing_nullable=True)
    op.alter_column('transfer_request', 'departure_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date the requested transfer left the camp',
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship22'), table_name='transfer_request')
    op.drop_index(op.f('IX_Relationship23'), table_name='transfer_request')
    op.alter_column('transfer_resource', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Transfer resource ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transfer_resource', 'transfer_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Amount's resource that will be transfer",
               existing_nullable=False)
    op.drop_index(op.f('IX_Relationship7'), table_name='transfer_resource')
    op.drop_index(op.f('IX_Relationship8'), table_name='transfer_resource')
    op.alter_column('user_achievement', 'is_unlocked',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Boolean to check if the achievement is unlocked',
               existing_nullable=False)
    op.alter_column('user_achievement', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when achievement was unlocked',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_achievement', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when achievement was unlocked',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_achievement', 'is_unlocked',
               existing_type=sa.BOOLEAN(),
               comment='Boolean to check if the achievement is unlocked',
               existing_nullable=False)
    op.create_index(op.f('IX_Relationship8'), 'transfer_resource', ['request_id'], unique=False)
    op.create_index(op.f('IX_Relationship7'), 'transfer_resource', ['resource_id'], unique=False)
    op.alter_column('transfer_resource', 'transfer_amount',
               existing_type=sa.INTEGER(),
               comment="Amount's resource that will be transfer",
               existing_nullable=False)
    op.alter_column('transfer_resource', 'id',
               existing_type=sa.INTEGER(),
               comment='Transfer resource ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship23'), 'transfer_request', ['to_camp_id'], unique=False)
    op.create_index(op.f('IX_Relationship22'), 'transfer_request', ['from_camp_id'], unique=False)
    op.alter_column('transfer_request', 'departure_date',
               existing_type=sa.DATE(),
               comment='Date the requested transfer left the camp',
               existing_nullable=False)
    op.alter_column('transfer_request', 'arrival_date',
               existing_type=sa.DATE(),
               comment='Date the requested transfer arrived at the camp',
               existing_nullable=True)
    op.alter_column('transfer_request', 'transfer_status',
               existing_type=postgresql.ENUM('EN PREPARACIÓN', 'DE CAMINO', 'LLEGÓ', name='transfer_status_enum'),
               comment="Transfer's status ('EN PREPARACIÓN', 'DE CAMINO', 'LLEGÓ')",
               existing_nullable=True)
    op.alter_column('transfer_request', 'request_status',
               existing_type=postgresql.ENUM('PENDIENTE', 'APROBADO', 'RECHAZADO', name='request_status_enum'),
               comment="Request's status ('PENDIENTE', 'APROBADA', 'RECHAZADA')",
               existing_nullable=False)
    op.alter_column('transfer_request', 'to_camp_id',
               existing_type=sa.INTEGER(),
               comment='Camp ID where the request is sent',
               existing_nullable=False)
    op.alter_column('transfer_request', 'from_camp_id',
               existing_type=sa.INTEGER(),
               comment='Camp ID from the request is made',
               existing_nullable=False)
    op.alter_column('transfer_request', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date when the request was created',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transfer_request', 'id',
               existing_type=sa.INTEGER(),
               comment='Transfer request ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transfer_participants', 'is_transfer_active',
               existing_type=sa.BOOLEAN(),
               comment='Attribute to check if the participant is in an active transfer\n',
               existing_nullable=False)
    op.alter_column('role', 'description',
               existing_type=sa.VARCHAR(length=100),
               comment='Short description about the role',
               existing_nullable=False)
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=40),
               comment="Role's name",
               existing_nullable=False)
    op.alter_column('role', 'id',
               existing_type=sa.INTEGER(),
               comment='Role ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('resource', 'category',
               existing_type=postgresql.ENUM('ALIMENTO', 'BEBIDAS', 'SEMILLAS', 'MEDICINAS', name='resource_category_enum'),
               comment="Resource's category ('ALIMENTOS', 'BEBIDAS', 'SEMILLAS','MEDICINAS')",
               existing_nullable=False)
    op.alter_column('resource', 'name',
               existing_type=sa.VARCHAR(length=40),
               comment="Resource's name",
               existing_nullable=False)
    op.alter_column('resource', 'id',
               existing_type=sa.INTEGER(),
               comment="Resource's id",
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship19'), 'profession_production', ['profession_id'], unique=False)
    op.create_index(op.f('IX_Relationship18'), 'profession_production', ['resource_id'], unique=False)
    op.alter_column('profession_production', 'production_quantity',
               existing_type=sa.INTEGER(),
               comment='Quantity of resources obtained in production',
               existing_nullable=False)
    op.alter_column('profession_production', 'id',
               existing_type=sa.INTEGER(),
               comment='Profession production ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship6'), 'profession_assignment', ['person_id'], unique=False)
    op.create_index(op.f('IX_Relationship5'), 'profession_assignment', ['profession_id'], unique=False)
    op.alter_column('profession_assignment', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Boolean to check if the assignment is active or not',
               existing_nullable=False)
    op.alter_column('profession_assignment', 'is_main_profession',
               existing_type=sa.BOOLEAN(),
               comment='Boolean to check if the assignment profession is its main job or not',
               existing_nullable=False)
    op.alter_column('profession_assignment', 'reason',
               existing_type=sa.VARCHAR(length=100),
               comment='Reason for the assignment in the profession',
               existing_nullable=False)
    op.alter_column('profession_assignment', 'end_date',
               existing_type=sa.DATE(),
               comment='Date when person ended its profession (in critical cases).',
               existing_nullable=True)
    op.alter_column('profession_assignment', 'start_date',
               existing_type=sa.DATE(),
               comment='Date when person started his profession in the camp',
               existing_nullable=False)
    op.alter_column('profession_assignment', 'id',
               existing_type=sa.INTEGER(),
               comment='Profession assignment ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('profession', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment="Profession's name",
               existing_nullable=False)
    op.alter_column('profession', 'is_critical',
               existing_type=sa.BOOLEAN(),
               comment='Attribute to check if a profession is in a critical situation or not. Basically if there is not workers available the situation is critical (true).',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('profession', 'id',
               existing_type=sa.INTEGER(),
               comment="Profession's id",
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship37'), 'production_log', ['profession_id'], unique=False)
    op.create_index(op.f('IX_Relationship36'), 'production_log', ['resource_id'], unique=False)
    op.create_index(op.f('IX_Relationship35'), 'production_log', ['person_id'], unique=False)
    op.create_index(op.f('IX_Relationship34'), 'production_log', ['camp_id'], unique=False)
    op.alter_column('production_log', 'expected_quantity',
               existing_type=sa.INTEGER(),
               comment='This is the expected quantity based on entity profession_production',
               existing_nullable=False)
    op.alter_column('production_log', 'actual_quantity',
               existing_type=sa.INTEGER(),
               comment='Actual quantity produced',
               existing_nullable=False)
    op.alter_column('production_log', 'id',
               existing_type=sa.INTEGER(),
               comment='ID for each production log',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship13'), 'person', ['camp_id'], unique=False)
    op.alter_column('person', 'id_card',
               existing_type=sa.VARCHAR(length=250),
               comment='Identification card for each Person',
               existing_nullable=False)
    op.alter_column('person', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='To check if person is active or not in the system',
               existing_nullable=False)
    op.alter_column('person', 'photo_url',
               existing_type=sa.TEXT(),
               comment="Photo's url where is save locally",
               existing_nullable=False)
    op.alter_column('person', 'camp_entry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the person arrived in the camp',
               existing_nullable=False)
    op.alter_column('person', 'health_status',
               existing_type=postgresql.ENUM('SANO', 'HERIDO', 'ENFERMO', 'MUERTO', name='health_status_enum'),
               comment="Person's health status ('SANO', 'HERIDO', 'ENFERMO', 'MUERTO')",
               existing_nullable=False)
    op.alter_column('person', 'current_status',
               existing_type=postgresql.ENUM('TRABAJANDO', 'EN EXPLORACIÓN', 'TRASLADANDO RECURSOS', 'LIBRE', name='current_status_enum'),
               comment="Current status ('TRABAJANDO', 'EN EXPLORACIÓN', 'TRASLADANDO RECURSOS', 'LIBRE')",
               existing_nullable=False)
    op.alter_column('person', 'height',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment="Person's height",
               existing_nullable=False)
    op.alter_column('person', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment="Person's weight",
               existing_nullable=False)
    op.alter_column('person', 'background_info',
               existing_type=sa.TEXT(),
               comment="Person's background info about its days surviving the apocalypse",
               existing_nullable=False)
    op.alter_column('person', 'age',
               existing_type=sa.INTEGER(),
               comment="Person's age",
               existing_nullable=False)
    op.alter_column('person', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               comment="Person's last name",
               existing_nullable=False)
    op.alter_column('person', 'name',
               existing_type=sa.VARCHAR(length=30),
               comment="Person's first name",
               existing_nullable=False)
    op.alter_column('person', 'id',
               existing_type=sa.INTEGER(),
               comment='Personal id for each person',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('permission', 'description',
               existing_type=sa.VARCHAR(length=100),
               comment="Permission's description about what it can do.",
               existing_nullable=False)
    op.alter_column('permission', 'name',
               existing_type=sa.VARCHAR(length=40),
               comment="Permission's name",
               existing_nullable=False)
    op.alter_column('permission', 'id',
               existing_type=sa.INTEGER(),
               comment='Permission ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship9'), 'inventory_resource', ['inventory_id'], unique=False)
    op.create_index(op.f('IX_Relationship10'), 'inventory_resource', ['resource_id'], unique=False)
    op.alter_column('inventory_resource', 'minimum_stock_level',
               existing_type=sa.INTEGER(),
               comment='Its the minimum level before notify the system',
               existing_nullable=False)
    op.alter_column('inventory_resource', 'quantity',
               existing_type=sa.INTEGER(),
               comment='Resource quantity that is stored in the inventory',
               existing_nullable=False)
    op.alter_column('inventory_resource', 'id',
               existing_type=sa.INTEGER(),
               comment='Inventory Resource ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship14'), 'inventory_movement', ['inventory_resource_id'], unique=False)
    op.alter_column('inventory_movement', 'movement_type',
               existing_type=postgresql.ENUM('SALIDA', 'INGRESO', 'TRANSFERENCIA', name='movement_type_enum'),
               comment="Movement type ('SALIDA', 'INGRESO', 'TRANSFERENCIA').",
               existing_nullable=False)
    op.alter_column('inventory_movement', 'quantity',
               existing_type=sa.INTEGER(),
               comment='Quantity of the resource being move',
               existing_nullable=False)
    op.alter_column('inventory_movement', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date when movement in inventory was made',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory_movement', 'id',
               existing_type=sa.INTEGER(),
               comment='Inventory Movement ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship15'), 'inventory', ['camp_id'], unique=False)
    op.alter_column('inventory', 'maximum_stock',
               existing_type=sa.INTEGER(),
               comment='Its the capacity of storage in the inventory',
               existing_nullable=False)
    op.alter_column('inventory', 'id',
               existing_type=sa.INTEGER(),
               comment="Inventory's id",
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship17'), 'exploration_loot', ['exploration_id'], unique=False)
    op.create_index(op.f('IX_Relationship16'), 'exploration_loot', ['resource_id'], unique=False)
    op.alter_column('exploration_loot', 'is_added_to_inventory',
               existing_type=sa.BOOLEAN(),
               comment='To check if the exploration loot have been added to the inventory or not',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('exploration_loot', 'quantity',
               existing_type=sa.INTEGER(),
               comment='Quantity of loot collected in the exploration',
               existing_nullable=False)
    op.alter_column('exploration_loot', 'id',
               existing_type=sa.INTEGER(),
               comment='Exploration loot ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship29'), 'exploration', ['camp_id'], unique=False)
    op.alter_column('exploration', 'estimated_days',
               existing_type=sa.INTEGER(),
               comment='Number of estimated days for a exploration',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('exploration', 'max_extra_days',
               existing_type=sa.INTEGER(),
               comment='Number of extra days a exploration could last',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('exploration', 'ration_per_person',
               existing_type=sa.INTEGER(),
               comment='Ration per person per day',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('exploration', 'extra_days',
               existing_type=sa.INTEGER(),
               comment='Extra days of exploration if they are needed',
               existing_nullable=False)
    op.alter_column('exploration', 'exploration_status',
               existing_type=postgresql.ENUM('EN PROCESO', 'COMPLETADA', 'CANCELADA', name='exploration_status_enum'),
               comment="Exploration's status ('EN PROCESO', 'COMPLETADA', 'CANCELADA')",
               existing_nullable=False)
    op.alter_column('exploration', 'return_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the explorers return to the camp',
               existing_nullable=True)
    op.alter_column('exploration', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the exploration started',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('exploration', 'id',
               existing_type=sa.INTEGER(),
               comment='Exploration ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship31'), 'daily_ration_log', ['camp_id'], unique=False)
    op.alter_column('daily_ration_log', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when daily ration were executed in the system (once per day)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('daily_ration_log', 'persons_fed',
               existing_type=sa.INTEGER(),
               comment='Number of persons who have been fed',
               existing_nullable=False)
    op.alter_column('daily_ration_log', 'id',
               existing_type=sa.INTEGER(),
               comment='ID for each daily ration log',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('camp', 'session_time',
               existing_type=sa.INTEGER(),
               comment='How mucho a session can long in minutes (its the cookies time session value) ',
               existing_nullable=False)
    op.alter_column('camp', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when camp was created',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('camp', 'location',
               existing_type=sa.VARCHAR(length=100),
               comment="Camp's location",
               existing_nullable=False)
    op.alter_column('camp', 'name',
               existing_type=sa.VARCHAR(length=40),
               comment="Camp's name",
               existing_nullable=False)
    op.alter_column('camp', 'id',
               existing_type=sa.INTEGER(),
               comment='Camp ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship25'), 'app_user', ['role_id'], unique=False)
    op.create_index(op.f('IX_Relationship12'), 'app_user', ['person_id'], unique=False)
    op.alter_column('app_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when user where created in the system',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('app_user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment="User's password",
               existing_nullable=False)
    op.alter_column('app_user', 'username',
               existing_type=sa.VARCHAR(length=20),
               comment='Unique username for each user',
               existing_nullable=False)
    op.alter_column('app_user', 'id',
               existing_type=sa.INTEGER(),
               comment='Personal id for each user',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('IX_Relationship32'), 'ai_log', ['person_id'], unique=False)
    op.create_index(op.f('IX_Relationship28'), 'ai_log', ['camp_id'], unique=False)
    op.alter_column('ai_log', 'final_user_decision',
               existing_type=sa.BOOLEAN(),
               comment='True = approved, False = disapproved',
               existing_nullable=False)
    op.alter_column('ai_log', 'evaluation_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="JSON with information needed for the system's AI",
               existing_nullable=False)
    op.alter_column('ai_log', 'ai_decision',
               existing_type=postgresql.ENUM('APROBADO', 'RECHAZADO', name='ai_decision_enum'),
               comment="Decision made by the sistem's AI",
               existing_nullable=False)
    op.alter_column('ai_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when AI log was made',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_log', 'decision_reason',
               existing_type=sa.TEXT(),
               comment="Reason for the system's AI decision",
               existing_nullable=False)
    op.alter_column('ai_log', 'id',
               existing_type=sa.INTEGER(),
               comment='AI log ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('achievement', 'icon_url',
               existing_type=sa.VARCHAR(length=255),
               comment="Icon's URL of local files",
               existing_nullable=False)
    op.alter_column('achievement', 'condition_value',
               existing_type=sa.INTEGER(),
               comment='It is the condition to unlock the achievement',
               existing_nullable=False)
    op.alter_column('achievement', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment="Achievement's description",
               existing_nullable=False)
    op.alter_column('achievement', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment="Achievement's name",
               existing_nullable=False)
    op.alter_column('achievement', 'id',
               existing_type=sa.INTEGER(),
               comment='Achievement ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
