"""init

Revision ID: 8a6306451f2e
Revises: 
Create Date: 2026-05-05 23:58:18.557268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a6306451f2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('camp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('session_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('category', sa.Enum('ALIMENTO', 'BEBIDAS', 'SEMILLAS', 'MEDICINAS', name='resource_category_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_ration_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persons_fed', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exploration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exploration_status', sa.Enum('EN PROCESO', 'COMPLETADA', 'CANCELADA', name='exploration_status_enum'), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('extra_days', sa.Integer(), nullable=False),
    sa.Column('ration_per_person', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_extra_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimated_days', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maximum_stock', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('background_info', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.Enum('TRABAJANDO', 'EN EXPLORACIÓN', 'TRASLADANDO RECURSOS', 'LIBRE', name='current_status_enum'), nullable=False),
    sa.Column('health_status', sa.Enum('SANO', 'HERIDO', 'ENFERMO', 'MUERTO', name='health_status_enum'), nullable=False),
    sa.Column('camp_entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id_card', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_quantity', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('transfer_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('from_camp_id', sa.Integer(), nullable=False),
    sa.Column('to_camp_id', sa.Integer(), nullable=False),
    sa.Column('request_status', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='request_status_enum'), nullable=False),
    sa.Column('transfer_status', sa.Enum('EN PREPARACIÓN', 'DE CAMINO', 'LLEGÓ', name='transfer_status_enum'), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('authorized_by', sa.String(length=80), nullable=True),
    sa.Column('is_resource_transfer', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['from_camp_id'], ['camp.id'], ),
    sa.ForeignKeyConstraint(['to_camp_id'], ['camp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ai_decision', sa.Enum('APROBADO', 'RECHAZADO', name='ai_decision_enum'), nullable=False),
    sa.Column('evaluation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('final_user_decision', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camp.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('exploration_loot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('exploration_id', sa.Integer(), nullable=False),
    sa.Column('is_added_to_inventory', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['exploration_id'], ['exploration.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exploration_member',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('exploration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exploration_id'], ['exploration.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'exploration_id')
    )
    op.create_table('inventory_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_stock_level', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camp.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('is_main_profession', sa.Boolean(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_participants',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('is_transfer_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['transfer_request.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'request_id')
    )
    op.create_table('transfer_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_amount', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['transfer_request.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('inventory_resource_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('SALIDA', 'INGRESO', 'TRANSFERENCIA', name='movement_type_enum'), nullable=False),
    sa.Column('transfer_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_resource_id'], ['inventory_resource.id'], ),
    sa.ForeignKeyConstraint(['transfer_request_id'], ['transfer_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievement',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievement')
    op.drop_table('inventory_movement')
    op.drop_table('transfer_resource')
    op.drop_table('transfer_participants')
    op.drop_table('profession_assignment')
    op.drop_table('production_log')
    op.drop_table('inventory_resource')
    op.drop_table('exploration_member')
    op.drop_table('exploration_loot')
    op.drop_table('app_user')
    op.drop_table('ai_log')
    op.drop_table('transfer_request')
    op.drop_table('role_permission')
    op.drop_table('profession_production')
    op.drop_table('person')
    op.drop_table('inventory')
    op.drop_table('exploration')
    op.drop_table('daily_ration_log')
    op.drop_table('role')
    op.drop_table('resource')
    op.drop_table('profession')
    op.drop_table('permission')
    op.drop_table('camp')
    op.drop_table('achievement')
    # ### end Alembic commands ###
